[nanobot]
config_version = 1
results_per_page = 5000

[logging]
level = "DEBUG"

[database]
connection = "build/nanobot.db"

[valve]
path = "src/schema/table.tsv"

[assets]
path = "src/assets/"

[templates]
path = "src/resources/"

[actions.file]
label = "File"
commands = []

[actions.sub_file_save]
label = "Save"
inputs = [
    { name = "message", label = "Save comment" }
]
commands = [
  ["make", "save"],
  ["git", "add", "--update"],
  ["git", "commit", "--message", "'{message}'"],
  ["git", "pull"],
  ["git", "push"]
]

[actions.sub_file_publish]
label = "Publish"
inputs = [
  { name = "tag", label = "Release Tag", default = "v{today}" },
]
commands = [
  ["make", "save"],
  ["git", "add", "--update"],
  ["git", "commit", "--message", "'{message}'"],
  ["git", "pull"],
  ["git", "push"],
  ["gh", "release", "create", "{tag}"],
  ["tdta", "purl-publish", "-i", "./", "-t", "CCN20230601", "-u", "'{username}'"]
]

[actions.export]
label = "Export"
commands = []

[actions.sub_export_cas_save]
label = "To CAS"
commands = [
  ["tdta", "export", "-db", "./build/nanobot.db", "-o", "./CCN20230601.json", "-c", "/tdt_datasets"]
]

[actions.sub_export_export_anndata]
label = "To AnnData"
commands = [
  ["tdta", "anndata", "-db", "./build/nanobot.db", "-j", "./CCN20230601.json", "-o", "/tdt_datasets/CCN20230601.h5ad", "-c", "/tdt_datasets"]
]

[actions.github]
label = "Version Control"
commands = []

[actions.sub_github_status]
label = "Status"
commands = [
  ["git", "-c", "color.ui=always", "status"],
]

[actions.sub_github_diff]
label = "Diff"
commands = [
  ["git", "-c", "color.ui=always", "diff"],
]

[actions.sub_github_fetch]
label = "Fetch"
commands = [
  ["git", "fetch"],
]

[actions.sub_github_pull]
label = "Pull"
commands = [
  ["git", "pull"],
]

[actions.sub_github_branch]
label = "Branch"
inputs = [
  { name = "branch_name", label = "Branch Name", default = "{username}-{today}", validate = "\\w+" }
]
commands = [
  ["git", "checkout", "main"],
  ["git", "pull"],
  ["git", "checkout", "-b", "{branch_name}"],
  ["git", "push", "--set-upstream", "origin", "{branch_name}"],
]

[actions.sub_github_commit]
label = "Commit"
inputs = [
    { name = "message", label = "Commit Message" }
]
commands = [
  ["git", "add", "--update"],
  ["git", "-c", "color.ui=always", "status"],
  ["git", "commit", "--message", "'{message}'"],
]

[actions.sub_github_commitandpush]
label = "Commit and Push"
inputs = [
    { name = "message", label = "Commit Message" }
]
commands = [
  ["git", "add", "--update"],
  ["git", "-c", "color.ui=always", "status"],
  ["git", "commit", "--message", "'{message}'"],
  ["git", "push"],
]

[actions.sub_github_push]
label = "Push"
commands = [
  ["git", "push"],
]

[actions.sub_github_pr]
label = "Pull Request"
inputs = [
  { name = "title", label = "Title" },
  { name = "body", label = "Body" },
]
commands = [
  ["gh", "pr", "create", "--title", "'{title}'", "--body", "'{body}'"],
]

[actions.sub_github_release]
label = "Release"
inputs = [
  { name = "tag", label = "Release Tag", default = "v{today}" },
]
commands = [
  ["git", "checkout", "main"],
  ["git", "pull"],
  ["git", "-c", "color.ui=always", "status"],
  ["gh", "release", "create", "{tag}"],
]

[actions.sub_github_purl]
label = "Publish PURL"
commands = [
  ["tdta", "purl-publish", "-i", "./", "-t", "CCN20230601", "-u", "'{username}'"]
]